// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderSystem.Infrastructure.Persistence;

#nullable disable

namespace OrderSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderSystemDbContext))]
    [Migration("20260924072609_AddOrderStatusHistory")]
    partial class AddOrderStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderSystem.Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("OnHandQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("on_hand_quantity");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("uq_inventories_product_variant_id");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventories_on_hand_quantity_non_negative", "on_hand_quantity >= 0");

                            t.HasCheckConstraint("ck_inventories_reserved_not_greater_than_on_hand", "reserved_quantity <= on_hand_quantity");

                            t.HasCheckConstraint("ck_inventories_reserved_quantity_non_negative", "reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OnHandQuantityDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("on_hand_delta");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_type");

                    b.Property<int>("ReservedQuantityDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_delta");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("ProductVariantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_inventory_transactions_variant_created_id");

                    b.HasIndex("ReferenceType", "ReferenceId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_inventory_transactions_reference_created")
                        .HasFilter("reference_id IS NOT NULL");

                    b.ToTable("inventory_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_transactions_adjustment_reason", "type <> 'Adjustment' OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");

                            t.HasCheckConstraint("ck_inventory_transactions_delta_shape", "(type = 'Receipt' AND on_hand_delta > 0 AND reserved_delta = 0) OR (type = 'Reserve' AND on_hand_delta = 0 AND reserved_delta > 0) OR (type = 'Release' AND on_hand_delta = 0 AND reserved_delta < 0) OR (type = 'Issue' AND on_hand_delta < 0 AND reserved_delta = on_hand_delta) OR (type = 'Adjustment' AND on_hand_delta <> 0 AND reserved_delta = 0)");

                            t.HasCheckConstraint("ck_inventory_transactions_non_zero_delta", "on_hand_delta <> 0 OR reserved_delta <> 0");

                            t.HasCheckConstraint("ck_inventory_transactions_order_reference", "type NOT IN ('Reserve', 'Release') OR (reference_type = 'Order' AND reference_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_transactions_reference_pair", "(reference_type IS NULL AND reference_id IS NULL) OR (reference_type IS NOT NULL AND reference_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_transactions_reference_type", "reference_type IS NULL OR reference_type IN ('Order', 'GoodsReceipt', 'Shipment', 'InventoryAdjustment')");

                            t.HasCheckConstraint("ck_inventory_transactions_type", "type IN ('Receipt', 'Reserve', 'Release', 'Issue', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ReservationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ReservationExpiresAt", "Id")
                        .HasDatabaseName("ix_orders_pending_expiration")
                        .HasFilter("status = 'PendingPayment'");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_orders_status_created_id");

                    b.HasIndex("UserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_orders_user_created_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_reservation_expires_after_created", "reservation_expires_at > created_at");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('PendingPayment', 'Confirmed', 'Processing', 'Completed', 'Cancelled', 'Expired')");

                            t.HasCheckConstraint("ck_orders_total_amount_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_order_items_product_variant_id");

                    b.HasIndex("OrderId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_items_order_variant");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_items_line_total_matches_unit_price", "line_total = quantity * unit_price");

                            t.HasCheckConstraint("ck_order_items_line_total_non_negative", "line_total >= 0");

                            t.HasCheckConstraint("ck_order_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_order_items_unit_price_non_negative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("ActorUserId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_order_status_history_actor_occurred_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("OrderId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_order_status_history_order_occurred_id");

                    b.ToTable("order_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_status_history_actor_type", "actor_type IN ('Customer', 'Admin', 'System')");

                            t.HasCheckConstraint("ck_order_status_history_actor_user", "(actor_type = 'System' AND actor_user_id IS NULL) OR (actor_type IN ('Customer', 'Admin') AND actor_user_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_order_status_history_admin_cancel_reason", "NOT (actor_type = 'Admin' AND to_status = 'Cancelled') OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");

                            t.HasCheckConstraint("ck_order_status_history_reason_code", "reason_code IN ('CustomerRequested', 'CustomerSupport', 'FraudSuspected', 'DuplicateOrder', 'InventoryIssue', 'PolicyViolation', 'Other')");

                            t.HasCheckConstraint("ck_order_status_history_reason_format", "reason IS NULL OR (reason = btrim(reason) AND length(reason) <= 500)");

                            t.HasCheckConstraint("ck_order_status_history_status_transition", "from_status IN ('PendingPayment', 'Confirmed', 'Processing', 'Completed', 'Cancelled', 'Expired') AND to_status IN ('PendingPayment', 'Confirmed', 'Processing', 'Completed', 'Cancelled', 'Expired') AND from_status <> to_status");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_products_status_created_at_id");

                    b.HasIndex("Status", "Name", "Id")
                        .HasDatabaseName("ix_products_status_name_id");

                    b.HasIndex("Status", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_products_status_updated_at_id");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_products_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_product_variants_sku");

                    b.HasIndex("ProductId", "Status", "Id")
                        .HasDatabaseName("ix_product_variants_product_id_status_id");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_current_price_non_negative", "current_price >= 0");

                            t.HasCheckConstraint("ck_product_variants_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_variants_sku_canonical", "length(sku) BETWEEN 1 AND 16 AND sku = upper(btrim(sku))");

                            t.HasCheckConstraint("ck_product_variants_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry_after_creation", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_replacement_not_self", "replaced_by_token_id IS NULL OR replaced_by_token_id <> id");

                            t.HasCheckConstraint("ck_refresh_tokens_replacement_requires_revocation", "replaced_by_token_id IS NULL OR revoked_at IS NOT NULL");

                            t.HasCheckConstraint("ck_refresh_tokens_revocation_after_creation", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_token_hash_canonical", "length(token_hash) = 64 AND token_hash = lower(token_hash) AND token_hash ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_users_normalized_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_not_empty", "length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_users_normalized_email_canonical", "normalized_email = lower(btrim(normalized_email))");

                            t.HasCheckConstraint("ck_users_password_hash_not_empty", "length(btrim(password_hash)) > 0");

                            t.HasCheckConstraint("ck_users_role", "role IN ('Customer', 'Admin')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.Inventory", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.ProductVariant", null)
                        .WithOne()
                        .HasForeignKey("OrderSystem.Domain.Inventories.Inventory", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_product_variants_product_variant_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.InventoryTransaction", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_product_variants_product_variant_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.Order", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("OrderSystem.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("OrderSystem.Domain.Products.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_product_variants_product_variant_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_status_history_users_actor_user_id");

                    b.HasOne("OrderSystem.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
