// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderSystem.Infrastructure.Persistence;

#nullable disable

namespace OrderSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderSystemDbContext))]
    [Migration("20261005133802_AddShipmentPersistence")]
    partial class AddShipmentPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderSystem.Domain.Idempotency.IdempotencyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DeleteAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_after");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("http_status_code");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResponseBodyJson")
                        .HasColumnType("text")
                        .HasColumnName("response_body_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Processing")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_requests");

                    b.HasIndex("DeleteAfter", "Id")
                        .HasDatabaseName("ix_idempotency_requests_terminal_cleanup")
                        .HasFilter("status = 'Completed'");

                    b.HasIndex("UserId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_idempotency_requests_user_operation_key");

                    b.ToTable("idempotency_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_requests_completion_time", "completed_at IS NULL OR completed_at >= created_at");

                            t.HasCheckConstraint("ck_idempotency_requests_create_order_completed", "operation <> 'CreateOrder'\r\nOR status <> 'Completed'\r\nOR (\r\n    resource_id IS NOT NULL\r\n    AND http_status_code = 201\r\n    AND response_body_json IS NOT NULL)");

                            t.HasCheckConstraint("ck_idempotency_requests_http_status_code", "http_status_code IS NULL OR http_status_code BETWEEN 100 AND 599");

                            t.HasCheckConstraint("ck_idempotency_requests_initiate_payment_completed", "operation <> 'InitiatePayment'\r\nOR status <> 'Completed'\r\nOR (\r\n    resource_id IS NOT NULL\r\n    AND http_status_code IS NULL\r\n    AND response_body_json IS NULL)");

                            t.HasCheckConstraint("ck_idempotency_requests_lifecycle", "(status = 'Processing'\r\n    AND resource_id IS NULL\r\n    AND http_status_code IS NULL\r\n    AND response_body_json IS NULL\r\n    AND completed_at IS NULL)\r\nOR\r\n(status = 'Completed'\r\n    AND resource_id IS NOT NULL\r\n    AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_idempotency_requests_operation", "operation IN ('CreateOrder', 'InitiatePayment')");

                            t.HasCheckConstraint("ck_idempotency_requests_request_hash_length", "octet_length(request_hash) = 32");

                            t.HasCheckConstraint("ck_idempotency_requests_response_body_size", "response_body_json IS NULL OR octet_length(response_body_json) <= 65536");

                            t.HasCheckConstraint("ck_idempotency_requests_retention", "expires_at > created_at AND delete_after > expires_at");

                            t.HasCheckConstraint("ck_idempotency_requests_status", "status IN ('Processing', 'Completed')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("OnHandQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("on_hand_quantity");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("uq_inventories_product_variant_id");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventories_on_hand_quantity_non_negative", "on_hand_quantity >= 0");

                            t.HasCheckConstraint("ck_inventories_reserved_not_greater_than_on_hand", "reserved_quantity <= on_hand_quantity");

                            t.HasCheckConstraint("ck_inventories_reserved_quantity_non_negative", "reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OnHandQuantityDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("on_hand_delta");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_type");

                    b.Property<int>("ReservedQuantityDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_delta");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("ProductVariantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_inventory_transactions_variant_created_id");

                    b.HasIndex("ReferenceType", "ReferenceId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_inventory_transactions_reference_created")
                        .HasFilter("reference_id IS NOT NULL");

                    b.ToTable("inventory_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_transactions_adjustment_reason", "type <> 'Adjustment' OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");

                            t.HasCheckConstraint("ck_inventory_transactions_delta_shape", "(type = 'Receipt' AND on_hand_delta > 0 AND reserved_delta = 0) OR (type = 'Reserve' AND on_hand_delta = 0 AND reserved_delta > 0) OR (type = 'Release' AND on_hand_delta = 0 AND reserved_delta < 0) OR (type = 'Issue' AND on_hand_delta < 0 AND reserved_delta = on_hand_delta) OR (type = 'Return' AND on_hand_delta > 0 AND reserved_delta = 0) OR (type = 'Adjustment' AND on_hand_delta <> 0 AND reserved_delta = 0)");

                            t.HasCheckConstraint("ck_inventory_transactions_non_zero_delta", "on_hand_delta <> 0 OR reserved_delta <> 0");

                            t.HasCheckConstraint("ck_inventory_transactions_order_reference", "type NOT IN ('Reserve', 'Release') OR (reference_type = 'Order' AND reference_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_transactions_reference_pair", "(reference_type IS NULL AND reference_id IS NULL) OR (reference_type IS NOT NULL AND reference_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_transactions_reference_type", "reference_type IS NULL OR reference_type IN ('Order', 'GoodsReceipt', 'Shipment', 'InventoryAdjustment')");

                            t.HasCheckConstraint("ck_inventory_transactions_return_reference", "type <> 'Return' OR (reference_type = 'Shipment' AND reference_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_transactions_type", "type IN ('Receipt', 'Reserve', 'Release', 'Issue', 'Return', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ReservationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ReservationExpiresAt", "Id")
                        .HasDatabaseName("ix_orders_pending_expiration")
                        .HasFilter("status = 'PendingPayment'");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_orders_status_created_id");

                    b.HasIndex("UserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_orders_user_created_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_reservation_expires_after_created", "reservation_expires_at > created_at");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('PendingPayment', 'Confirmed', 'Processing', 'Completed', 'FulfillmentFailed', 'Cancelled', 'Expired')");

                            t.HasCheckConstraint("ck_orders_total_amount_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_order_items_product_variant_id");

                    b.HasIndex("OrderId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_items_order_variant");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_items_line_total_matches_unit_price", "line_total = quantity * unit_price");

                            t.HasCheckConstraint("ck_order_items_line_total_non_negative", "line_total >= 0");

                            t.HasCheckConstraint("ck_order_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_order_items_unit_price_non_negative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("ActorUserId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_order_status_history_actor_occurred_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("OrderId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_order_status_history_order_occurred_id");

                    b.ToTable("order_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_status_history_actor_type", "actor_type IN ('Customer', 'Admin', 'System')");

                            t.HasCheckConstraint("ck_order_status_history_actor_user", "(actor_type = 'System' AND actor_user_id IS NULL) OR (actor_type IN ('Customer', 'Admin') AND actor_user_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_order_status_history_admin_cancel_reason", "NOT (actor_type = 'Admin' AND to_status = 'Cancelled') OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");

                            t.HasCheckConstraint("ck_order_status_history_reason_code", "reason_code IN ('CustomerRequested', 'CustomerSupport', 'FraudSuspected', 'DuplicateOrder', 'InventoryIssue', 'PolicyViolation', 'Other', 'ReservationExpired', 'ShipmentCreated', 'ShipmentDelivered', 'ShipmentReturned')");

                            t.HasCheckConstraint("ck_order_status_history_reason_format", "reason IS NULL OR (reason = btrim(reason) AND length(reason) <= 500)");

                            t.HasCheckConstraint("ck_order_status_history_status_transition", "from_status IN ('PendingPayment', 'Confirmed', 'Processing', 'Completed', 'FulfillmentFailed', 'Cancelled', 'Expired') AND to_status IN ('PendingPayment', 'Confirmed', 'Processing', 'Completed', 'FulfillmentFailed', 'Cancelled', 'Expired') AND from_status <> to_status");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("GatewayIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("gateway_idempotency_key");

                    b.Property<DateTimeOffset?>("LastStatusCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_checked_at");

                    b.Property<DateTimeOffset?>("ManualReviewRequiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manual_review_required_at");

                    b.Property<DateTimeOffset?>("NextRefundAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_refund_attempt_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_refund_id");

                    b.Property<int>("RefundAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("refund_attempt_count");

                    b.Property<string>("RefundIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refund_idempotency_key");

                    b.Property<DateTimeOffset?>("RefundRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refund_requested_at");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<string>("Scenario")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scenario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("GatewayIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_gateway_idempotency_key");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_order_id");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_provider_payment_id");

                    b.HasIndex("ProviderRefundId")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_provider_refund_id");

                    b.HasIndex("RefundIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_refund_idempotency_key");

                    b.HasIndex("NextRefundAttemptAt", "Id")
                        .HasDatabaseName("ix_payments_refund_pending")
                        .HasFilter("status = 'RefundPending' AND manual_review_required_at IS NULL");

                    b.HasIndex("LastStatusCheckedAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_payments_unresolved")
                        .HasFilter("status IN ('Pending', 'Processing')");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_non_negative", "amount >= 0");

                            t.HasCheckConstraint("ck_payments_failure_code_lifecycle", "(status = 'Failed' AND failure_code IS NOT NULL AND failure_code = btrim(failure_code) AND length(failure_code) BETWEEN 1 AND 64) OR (status <> 'Failed' AND failure_code IS NULL)");

                            t.HasCheckConstraint("ck_payments_refund_attempt_count_non_negative", "refund_attempt_count >= 0");

                            t.HasCheckConstraint("ck_payments_refund_lifecycle", "(status IN ('Pending', 'Processing', 'Succeeded', 'Failed') AND refund_idempotency_key IS NULL AND provider_refund_id IS NULL AND refund_requested_at IS NULL AND refund_attempt_count = 0 AND next_refund_attempt_at IS NULL AND manual_review_required_at IS NULL AND refunded_at IS NULL) OR (status = 'RefundPending' AND refund_idempotency_key IS NOT NULL AND refund_idempotency_key = btrim(refund_idempotency_key) AND length(refund_idempotency_key) BETWEEN 1 AND 128 AND provider_refund_id IS NULL AND refund_requested_at IS NOT NULL AND refunded_at IS NULL AND ((manual_review_required_at IS NULL AND next_refund_attempt_at IS NOT NULL) OR (manual_review_required_at IS NOT NULL AND next_refund_attempt_at IS NULL))) OR (status = 'Refunded' AND refund_idempotency_key IS NOT NULL AND refund_idempotency_key = btrim(refund_idempotency_key) AND length(refund_idempotency_key) BETWEEN 1 AND 128 AND provider_refund_id IS NOT NULL AND provider_refund_id = btrim(provider_refund_id) AND length(provider_refund_id) BETWEEN 1 AND 128 AND refund_requested_at IS NOT NULL AND refunded_at IS NOT NULL AND refunded_at >= refund_requested_at AND next_refund_attempt_at IS NULL AND manual_review_required_at IS NULL)");

                            t.HasCheckConstraint("ck_payments_scenario", "scenario IS NULL OR scenario IN ('SUCCESS', 'FAILED', 'CLIENT_RESPONSE_LOST', 'PROVIDER_RESPONSE_LOST', 'DELAYED_SUCCESS')");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Pending', 'Processing', 'Succeeded', 'Failed', 'RefundPending', 'Refunded')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Payments.ProviderPaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_event_id");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_payment_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_provider_payment_events");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_payment_events_provider_event");

                    b.HasIndex("Provider", "ProviderPaymentId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_provider_payment_events_provider_payment_occurred_id");

                    b.ToTable("provider_payment_events", (string)null);
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_products_status_created_at_id");

                    b.HasIndex("Status", "Name", "Id")
                        .HasDatabaseName("ix_products_status_name_id");

                    b.HasIndex("Status", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_products_status_updated_at_id");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_products_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_product_variants_sku");

                    b.HasIndex("ProductId", "Status", "Id")
                        .HasDatabaseName("ix_product_variants_product_id_status_id");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_current_price_non_negative", "current_price >= 0");

                            t.HasCheckConstraint("ck_product_variants_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_variants_sku_canonical", "length(sku) BETWEEN 1 AND 16 AND sku = upper(btrim(sku))");

                            t.HasCheckConstraint("ck_product_variants_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("RestockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restocked_at");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_shipments_order_id");

                    b.HasIndex("Status", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_shipments_status_updated_id");

                    b.ToTable("shipments", null, t =>
                        {
                            t.HasCheckConstraint("ck_shipments_failure_reason_lifecycle", "(status = 'DeliveryFailed' AND failure_reason IS NOT NULL AND failure_reason = btrim(failure_reason) AND length(failure_reason) BETWEEN 1 AND 500) OR (status <> 'DeliveryFailed' AND failure_reason IS NULL)");

                            t.HasCheckConstraint("ck_shipments_lifecycle_timestamps_after_created", "(shipped_at IS NULL OR shipped_at >= created_at) AND (delivered_at IS NULL OR delivered_at >= created_at) AND (returned_at IS NULL OR returned_at >= created_at) AND (restocked_at IS NULL OR restocked_at >= created_at)");

                            t.HasCheckConstraint("ck_shipments_status", "status IN ('Pending', 'Picking', 'Packed', 'Shipped', 'OutForDelivery', 'Delivered', 'DeliveryFailed', 'Returning', 'Returned')");

                            t.HasCheckConstraint("ck_shipments_updated_after_created", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry_after_creation", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_replacement_not_self", "replaced_by_token_id IS NULL OR replaced_by_token_id <> id");

                            t.HasCheckConstraint("ck_refresh_tokens_replacement_requires_revocation", "replaced_by_token_id IS NULL OR revoked_at IS NOT NULL");

                            t.HasCheckConstraint("ck_refresh_tokens_revocation_after_creation", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_token_hash_canonical", "length(token_hash) = 64 AND token_hash = lower(token_hash) AND token_hash ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_users_normalized_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_not_empty", "length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_users_normalized_email_canonical", "normalized_email = lower(btrim(normalized_email))");

                            t.HasCheckConstraint("ck_users_password_hash_not_empty", "length(btrim(password_hash)) > 0");

                            t.HasCheckConstraint("ck_users_role", "role IN ('Customer', 'Admin')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Infrastructure.Payments.FakeProvider.FakeProviderOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation_type");

                    b.Property<string>("ParentProviderPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parent_provider_payment_id");

                    b.Property<string>("ProviderResourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_resource_id");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scenario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_fake_provider_operations");

                    b.HasIndex("OperationType", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_fake_provider_operations_type_key");

                    b.HasIndex("OperationType", "ProviderResourceId")
                        .IsUnique()
                        .HasDatabaseName("uq_fake_provider_operations_type_resource");

                    b.ToTable("operations", "fake_provider", t =>
                        {
                            t.HasCheckConstraint("ck_fake_provider_operations_amount_non_negative", "amount >= 0");

                            t.HasCheckConstraint("ck_fake_provider_operations_available_after_created", "available_at IS NULL OR available_at >= created_at");

                            t.HasCheckConstraint("ck_fake_provider_operations_parent_identity", "(operation_type = 'CreatePayment' AND parent_provider_payment_id IS NULL) OR (operation_type = 'RefundPayment' AND parent_provider_payment_id IS NOT NULL AND parent_provider_payment_id = btrim(parent_provider_payment_id) AND length(parent_provider_payment_id) BETWEEN 1 AND 128)");

                            t.HasCheckConstraint("ck_fake_provider_operations_scenario", "scenario IN ('SUCCESS', 'FAILED', 'CLIENT_RESPONSE_LOST', 'PROVIDER_RESPONSE_LOST', 'DELAYED_SUCCESS')");

                            t.HasCheckConstraint("ck_fake_provider_operations_status", "status IN ('Pending', 'Processing', 'Succeeded', 'Failed')");

                            t.HasCheckConstraint("ck_fake_provider_operations_type", "operation_type IN ('CreatePayment', 'RefundPayment')");

                            t.HasCheckConstraint("ck_fake_provider_operations_updated_after_created", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Idempotency.IdempotencyRequest", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_requests_users_user_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.Inventory", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.ProductVariant", null)
                        .WithOne()
                        .HasForeignKey("OrderSystem.Domain.Inventories.Inventory", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_product_variants_product_variant_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Inventories.InventoryTransaction", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_product_variants_product_variant_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.Order", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("OrderSystem.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("OrderSystem.Domain.Products.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_product_variants_product_variant_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_status_history_users_actor_user_id");

                    b.HasOne("OrderSystem.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Payments.Payment", b =>
                {
                    b.HasOne("OrderSystem.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Payments.ProviderPaymentEvent", b =>
                {
                    b.HasOne("OrderSystem.Domain.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provider_payment_events_payments_payment_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderSystem.Domain.Shipments.Shipment", b =>
                {
                    b.HasOne("OrderSystem.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_orders_order_id");
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
