// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderSystem.Infrastructure.Persistence;

#nullable disable

namespace OrderSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderSystemDbContext))]
    partial class OrderSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderSystem.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_products_status_created_at_id");

                    b.HasIndex("Status", "Name", "Id")
                        .HasDatabaseName("ix_products_status_name_id");

                    b.HasIndex("Status", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_products_status_updated_at_id");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_products_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_product_variants_sku");

                    b.HasIndex("ProductId", "Status", "Id")
                        .HasDatabaseName("ix_product_variants_product_id_status_id");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_current_price_non_negative", "current_price >= 0");

                            t.HasCheckConstraint("ck_product_variants_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_product_variants_sku_canonical", "length(sku) BETWEEN 1 AND 16 AND sku = upper(btrim(sku))");

                            t.HasCheckConstraint("ck_product_variants_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry_after_creation", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_replacement_not_self", "replaced_by_token_id IS NULL OR replaced_by_token_id <> id");

                            t.HasCheckConstraint("ck_refresh_tokens_replacement_requires_revocation", "replaced_by_token_id IS NULL OR revoked_at IS NOT NULL");

                            t.HasCheckConstraint("ck_refresh_tokens_revocation_after_creation", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_token_hash_canonical", "length(token_hash) = 64 AND token_hash = lower(token_hash) AND token_hash ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_users_normalized_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_not_empty", "length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_users_normalized_email_canonical", "normalized_email = lower(btrim(normalized_email))");

                            t.HasCheckConstraint("ck_users_password_hash_not_empty", "length(btrim(password_hash)) > 0");

                            t.HasCheckConstraint("ck_users_role", "role IN ('Customer', 'Admin')");
                        });
                });

            modelBuilder.Entity("OrderSystem.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("OrderSystem.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderSystem.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("OrderSystem.Domain.Users.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("OrderSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
